config/routes.rb
Rails.application.routes.draw do
  root to: "lexemes#index"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  
  resources :users#, except: [:new]
  get '/sign_up' => 'users#new', as: 'sign_up'
  patch '/promote/:id' => 'users#promote', as: 'promote'
 
  resources :lexemes
  get '/search' => 'lexemes#search', as: 'search'
  get '/tts/:lang/:query_string/' => 'lexemes#tts', as: 'tts'
  
  resources :senses, only: [:create, :update, :destroy]
  patch '/approve/:id' => 'senses#approve', as: 'approve'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/senses_controller.rb
class SensesController < ApplicationController
  before_action :set_sense, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:edit, :update, :destroy, :approve]
  before_action :require_admin, only: [:edit, :update, :destroy, :approve]
  
  # GET /senses
  # GET /senses.json
  def index
    @senses = Sense.all
  end

  # GET /senses/1
  # GET /senses/1.json
  def show
  end

  # GET /senses/new
  def new
    @sense = Sense.new
  end

  # GET /senses/1/edit
  def edit
  end

  # POST /senses
  # POST /senses.json
  def create
    @sense = Sense.new(sense_params)

    respond_to do |format|
      if @sense.save
        format.html { redirect_to @sense.lexeme, notice: 'Sense was successfully created.' }
        format.json { render :show, status: :created, location: @sense }
      else
        format.html { render :new }
        format.json { render json: @sense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /senses/1
  # PATCH/PUT /senses/1.json
  def update
    respond_to do |format|
      if @sense.update(sense_params)
        format.html { redirect_to @sense, notice: 'Sense was successfully updated.' }
        format.json { render :show, status: :ok, location: @sense }
      else
        format.html { render :edit }
        format.json { render json: @sense.errors, status: :unprocessable_entity }
      end
    end
  end

  def approve
    respond_to do |format|
      begin
        @sense = Sense.find_by(id: params[:id])
        raise('No such meaning found') if @sense.nil?
        raise('Already approved') if @sense.approve
        raise(@sense.errors) if !@sense.update(approve: true)

        format.html { redirect_to(@sense.lexeme, notice: 'Meaning was successfully approved.') }
        format.json { render(:show, status: :ok, location: @user) }
      rescue Exception => err
        format.html { redirect_to(root_path, notice: err.message) }
        format.json { render(json: err.message, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /senses/1
  # DELETE /senses/1.json
  def destroy
    @sense.destroy
    respond_to do |format|
      format.html { redirect_to senses_url, notice: 'Sense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sense
      @sense = Sense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sense_params
      params.require(:sense).permit(:word_class, :content, :lexeme_id)
    end

    def require_login
    end
end

app/views/senses/_form.html.erb
<%= form_with(model: sense, local: true) do |form| %>
  <% if sense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sense.errors.count, "error") %> prohibited this sense from being saved:</h2>

      <ul>
      <% sense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.number_field :type, id: :sense_type %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :sense_content %>
  </div>

  <div class="field">
    <%= form.label :lexeme_id %>
    <%= form.text_field :lexeme_id, id: :sense_lexeme_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/senses/edit.html.erb
<h1>Editing Sense</h1>

<%= render 'form', sense: @sense %>

<%= link_to 'Show', @sense %> |
<%= link_to 'Back', senses_path %>

app/views/senses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Senses</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Content</th>
      <th>Lexeme</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @senses.each do |sense| %>
      <tr>
        <td><%= sense.type %></td>
        <td><%= sense.content %></td>
        <td><%= sense.lexeme %></td>
        <td><%= link_to 'Show', sense %></td>
        <td><%= link_to 'Edit', edit_sense_path(sense) %></td>
        <td><%= link_to 'Destroy', sense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sense', new_sense_path %>

app/views/senses/new.html.erb
<h1>New Sense</h1>

<%= render 'form', sense: @sense %>

<%= link_to 'Back', senses_path %>

app/views/senses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @sense.type %>
</p>

<p>
  <strong>Content:</strong>
  <%= @sense.content %>
</p>

<p>
  <strong>Lexeme:</strong>
  <%= @sense.lexeme %>
</p>

<%= link_to 'Edit', edit_sense_path(@sense) %> |
<%= link_to 'Back', senses_path %>