config/routes.rb
Rails.application.routes.draw do
  root to: "lexemes#index"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  
  resources :users#, except: [:new]
  get '/sign_up' => 'users#new', as: 'sign_up'
  patch '/promote/:id' => 'users#promote', as: 'promote'
 
  resources :lexemes
  get '/search' => 'lexemes#search', as: 'search'
  get '/tts/:lang/:query_string/' => 'lexemes#tts', as: 'tts'
  
  resources :senses, only: [:create, :update, :destroy]
  patch '/approve/:id' => 'senses#approve', as: 'approve'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lexeme.rb
class Lexeme < ApplicationRecord
  has_many(:senses)

  WORD_CLASS_PAIRS = [
    [:Noun, 0],
    [:Verb, 1],
    [:Adjective, 2],
    [:Adverb, 3],
    [:Particle, 4],
    [:Expression, 5],
  ].freeze

  WORD_CLASSES = WORD_CLASS_PAIRS.map { |x| x[0] }.freeze
end

app/controllers/lexemes_controller.rb
class LexemesController < ApplicationController
  before_action :set_lexeme, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  
  # Source: https://gist.github.com/rewonc/0024ec71bb589be18bd7
  # Pipes to Google Translate's Text-To-Speech service
  def tts
    queryString = params[:query_string] #.gsub(. . ., '')
    lang = params[:lang] #Language code; see https://sites.google.com/site/tomihasa/google-language-codes
    require 'net/http'
    url = URI.parse('http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=' + lang + '&q=' + URI::encode(queryString))
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
    send_data(res.body, :disposition => "inline", :filename => "sound.mp3", :type => "audio/mpeg")
  end

  # GET /lexemes
  # GET /lexemes.json
  def index
    @lexemes = Lexeme.all
  end

  def search
    fuzzyQuery = "%#{params[:q].downcase.split('').join('%')}%"
    @lexemes = Lexeme
      .joins('LEFT JOIN senses ON lexemes.id = senses.id')
      .where('LOWER(headword) LIKE ? OR LOWER(content) LIKE ?', fuzzyQuery, fuzzyQuery)
      .distinct
    
    respond_to do |format|
      format.html { render(:index) }
    end
  end

  # GET /lexemes/1
  # GET /lexemes/1.json
  def show
  end

  # GET /lexemes/new
  def new
    @lexeme = Lexeme.new
  end

  # GET /lexemes/1/edit
  def edit
  end

  # POST /lexemes
  # POST /lexemes.json
  def create
    @lexeme = Lexeme.new(lexeme_params)

    respond_to do |format|
      if @lexeme.save
        format.html { redirect_to @lexeme, notice: 'Lexeme was successfully created.' }
        format.json { render :show, status: :created, location: @lexeme }
      else
        format.html { render :new }
        format.json { render json: @lexeme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lexemes/1
  # PATCH/PUT /lexemes/1.json
  def update
    respond_to do |format|
      if @lexeme.update(lexeme_params)
        format.html { redirect_to @lexeme, notice: 'Lexeme was successfully updated.' }
        format.json { render :show, status: :ok, location: @lexeme }
      else
        format.html { render :edit }
        format.json { render json: @lexeme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lexemes/1
  # DELETE /lexemes/1.json
  def destroy
    @lexeme.destroy
    respond_to do |format|
      format.html { redirect_to lexemes_url, notice: 'Lexeme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lexeme
      @lexeme = Lexeme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lexeme_params
      params.require(:lexeme).permit(:headword)
    end
end

app/views/lexemes/_form.html.erb
<%= form_with(model: lexeme, local: true) do |form| %>
  <% if lexeme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lexeme.errors.count, "error") %> prohibited this lexeme from being saved:</h2>

      <ul>
      <% lexeme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :word %>
    <%= form.text_field :headword, id: :lexeme_headword %>
  </div>

  <div class="actions">
    <%= form.submit "Add word to dictionary" %>
  </div>
<% end %>

app/views/lexemes/edit.html.erb
<h1>Editing Lexeme</h1>

<%= render 'form', lexeme: @lexeme %>

<%= link_to 'Show', @lexeme %> |
<%= link_to 'Back', lexemes_path %>

app/views/lexemes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lexemes</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lexemes.each do |lexeme| %>
      <tr>
        <td><%= lexeme.headword %></td>
        <td><%= link_to 'Show', lexeme %></td>
        <td><%= link_to 'Edit', edit_lexeme_path(lexeme) %></td>
        <td><%= link_to 'Destroy', lexeme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lexeme', new_lexeme_path %>

app/views/lexemes/new.html.erb
<h1>New Word</h1>

<%= render 'form', lexeme: @lexeme %>

<%= link_to 'Back', lexemes_path %>

app/views/lexemes/show.html.erb
<p id="notice"><%= notice %></p>

<% showId = "show#{@lexeme.id}" %>
<% editId = "edit#{@lexeme.id}" %>

<div id="<%= showId %>" class="show">
  <div>
    <strong><%= @lexeme.headword %></strong>
    <% uriencoded = URI.escape(@lexeme.headword, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")) %>
    <audio src="<%= "/tts/en/#{uriencoded}" %>" controls></audio>
    <%= link_to('Edit', '#', id: :edit, onclick: "ajaxEdit('#{lexeme_path(@lexeme)}.json', #{@lexeme.id})") %>
  </div>
  <div>
    <ol>
      <% @lexeme.senses.select { |sense| sense.approve }.each do |sense| %>
        <li>
          <strong><%= Lexeme::WORD_CLASSES[sense.word_class] %></strong>
          <%= sense.content %>
        </li>
      <% end %>
    </ol>

    <div class="pending">
      <strong>Pending:</strong>
      <ol>
        <% @lexeme.senses.select { |sense| !sense.approve }.each do |sense| %>
          <li>
            <strong><%= Lexeme::WORD_CLASSES[sense.word_class] %></strong>
            <%= sense.content -%>
            <% if !current_user.nil? && current_user.admin? -%>
              <%= button_to('Approve', approve_path(sense.id), method: :patch) %>
            <% end -%>
          </li>
        <% end %>
      </ol>
    </div>

    <%# Add a new sense %>
    <% options =  %>
    <%= form_with(model: Sense.new) do |form| %>
      <%= form.select(:word_class, options_for_select(Lexeme::WORD_CLASS_PAIRS)) %>
 
      <%= form.text_field :content, id: :sense_content %>
      <%= form.hidden_field(:lexeme_id, value: @lexeme.id) %>

      <%= form.submit 'Add meaning' %>
    <% end %>
    
  </div>
</div>
<div id="<%= editId %>" class="edit">
  <%= form_with(model: @lexeme, method: :put) do |form| %>

    <div class="field">
      <strong>Word:</strong>
      <%= form.text_field :headword, value: @lexeme.headword, id: "lexeme_headword#{@lexeme.id}" %>
    </div>

    <div class="actions">
      <%= form.submit 'Save' %>
    </div>
  <% end %>
</div>

<%= link_to 'Back', lexemes_path %>

<script>
/*
  (function () {
    'use strict';

    var obj = document.getElementById('edit');
    obj.addEventListener('click', function () {
      apiRequest('<%= "#{lexeme_path(@lexeme)}.json" %>').then(function (resp) {
        document.getElementById('<%= showId %>').style.display = 'none';
        document.getElementById('<%= editId %>').style.display = 'block';
      });
      
    });
  })();*/
</script>