config/routes.rb
Rails.application.routes.draw do
  root to: "lexemes#index"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  
  resources :users#, except: [:new]
  get '/sign_up' => 'users#new', as: 'sign_up'
  patch '/promote/:id' => 'users#promote', as: 'promote'
 
  resources :lexemes
  get '/search' => 'lexemes#search', as: 'search'
  get '/tts/:lang/:query_string/' => 'lexemes#tts', as: 'tts'
  
  resources :senses, only: [:create, :update, :destroy]
  patch '/approve/:id' => 'senses#approve', as: 'approve'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dictionary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <div class="item"><strong>Dictionary</strong></div>
        <div class="item"><%= button_to('Word List', lexemes_path, method: :get) %></div>
        <div class="item"><%= button_to('User List', users_path, method: :get) %></div>
        <div class="item">
          <%= form_with(url: search_path, local: true, method: :get) do |form| %>
            <%= form.text_field :q %>
            <%= form.submit 'Fuzzy Search' %>
          <% end %>
        </div>

        <%# Promote user if only user available %>
        <% if signed_in? && User.count == 1 && !current_user.nil? && !current_user.admin? %>
          <div class="item">
            <%= button_to('Become Admin!', promote_path(current_user.id), method: :patch) %>
          </div>
        <% end %>

        <%# Button for session and user management %>
        <div class="item">
          <% if !signed_in? %>
            <% if !current_page?(login_path) %>
              <%= button_to('Login', login_path, method: 'get') %>
            <% end %>
            <% if !current_page?(sign_up_path) %>
              <%= button_to('Sign Up', sign_up_path, method: 'get') %>
            <% end %>
          <% else %>
            <%= button_to('Logout', logout_path, method: 'delete') %>
          <% end %>
        </div>
      </nav>
    </header>

    <section>
      <article>
        <%= yield %>
      </article>
    </section>
  </body>
</html>